export const COMPONENT_KEYS = {
  CATEGORY_CAROUSEL: 'CATEGORY_CAROUSEL',
  PRODUCT_CAROUSEL: 'PRODUCT_CAROUSEL',
  PRODUCT_MASONRY_GRID: 'PRODUCT_MASONRY_GRID',
  VENDOR_CAROUSEL: 'VENDOR_CAROUSEL',
}
